import { useState } from 'react';
import { motion } from 'motion/react';
import {
  ClipboardCheck,
  HelpCircle,
  Copy,
  Check,
  Printer,
  Scale,
  Sparkles,
  AlertTriangle,
  FileWarning,
  Target,
  MessageCircleQuestion,
} from 'lucide-react';
import { LawyerQuestion, MissingProtection, DocumentSummary } from '../types/legal.js';

interface LawyerPrepKitProps {
  summary: DocumentSummary;
  questions: LawyerQuestion[];
  missingProtections: MissingProtection[];
  keyNegotiationPoints: string[];
  criticalChecklist: string[];
  highContrast: boolean;
}

/** Priority badge colours */
function priorityBadge(priority: string) {
  if (priority === 'HIGH')
    return 'bg-rose-500/15 text-rose-300 border-rose-500/35 shadow-[0_0_8px_rgba(244,63,94,0.25)]';
  if (priority === 'MEDIUM')
    return 'bg-amber-500/15 text-amber-300 border-amber-500/35';
  return 'bg-slate-700/50 text-slate-300 border-slate-600/40';
}

function priorityDot(priority: string) {
  if (priority === 'HIGH') return { ping: 'bg-rose-400', dot: 'bg-rose-400' };
  if (priority === 'MEDIUM') return { ping: 'bg-amber-400', dot: 'bg-amber-400' };
  return { ping: 'bg-slate-400', dot: 'bg-slate-500' };
}

/** Importance badge for missing protections */
function importanceBadge(importance: string) {
  if (importance === 'HIGH')
    return 'bg-rose-500/15 text-rose-300 border-rose-500/35';
  if (importance === 'MEDIUM')
    return 'bg-amber-500/15 text-amber-300 border-amber-500/35';
  return 'bg-violet-500/15 text-violet-300 border-violet-500/35';
}

export function LawyerPrepKit({
  summary,
  questions,
  missingProtections,
  keyNegotiationPoints,
  criticalChecklist,
}: LawyerPrepKitProps) {
  const [copied, setCopied] = useState(false);
  const [checkedItems, setCheckedItems] = useState<Record<number, boolean>>({});

  const generateMarkdownBrief = () => {
    let md = `# LEGAL CONSULTATION PREP KIT: ${summary.documentType}\n`;
    md += `Overall Risk Score: ${summary.overallRiskScore}/100 (${summary.overallRiskLevel} Risk)\n`;
    md += `Generated by LexiGuard AI for Legal Assistance & Access\n\n`;
    md += `## EXECUTIVE SUMMARY\n${summary.executiveSummary}\n\n`;
    md += `## 1. CRITICAL RED FLAGS CHECKLIST\n`;
    criticalChecklist.forEach((item, i) => { md += `${i + 1}. [ ] ${item}\n`; });
    md += `\n## 2. QUESTIONS TO ASK YOUR ATTORNEY\n`;
    questions.forEach((q, i) => {
      md += `### ${i + 1}. [${q.priority}] ${q.topic}: ${q.question}\nContext: ${q.context}\n\n`;
    });
    if (missingProtections.length > 0) {
      md += `## 3. MISSING LEGAL SAFEGUARDS TO INSERT\n`;
      missingProtections.forEach((m, i) => {
        md += `### ${i + 1}. ${m.title} (${m.importance})\n${m.description}\nProposed Language: "${m.recommendedAddition}"\n\n`;
      });
    }
    md += `## 4. KEY NEGOTIATION PRIORITIES\n`;
    keyNegotiationPoints.forEach(pt => { md += `- ${pt}\n`; });
    md += `\n---\nLEGAL NOTICE: Educational and informational only; does not replace formal legal counsel.\n`;
    return md;
  };

  const handleCopyBrief = () => {
    navigator.clipboard.writeText(generateMarkdownBrief());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const toggleCheck = (idx: number) =>
    setCheckedItems(prev => ({ ...prev, [idx]: !prev[idx] }));

  const checkedCount = Object.values(checkedItems).filter(Boolean).length;

  return (
    <div id="lawyer-prep-kit" role="region" aria-label="Lawyer Consultation Checklist" className="space-y-5">

      {/* ─────────────────────────────────────────── */}
      {/* SECTION HEADER + ACTIONS                    */}
      {/* ─────────────────────────────────────────── */}
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="flex items-start gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-violet-500/30 to-indigo-500/20 border border-violet-500/30 flex items-center justify-center shadow-[0_0_15px_rgba(139,92,246,0.2)] shrink-0">
            <Scale className="w-5 h-5 text-violet-400" />
          </div>
          <div>
            <h2 className="text-lg font-extrabold text-white tracking-tight">Lawyer Consultation Prep Kit</h2>
            <p className="text-xs text-slate-400 font-medium max-w-xl leading-relaxed mt-0.5">
              Maximise your consultation efficiency — a prioritised issue list, missing clause checklist, and negotiation counter-proposals.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2.5 shrink-0">
          <motion.button
            type="button"
            whileHover={{ scale: 1.03 }}
            whileTap={{ scale: 0.97 }}
            onClick={handleCopyBrief}
            className="px-4 py-2 rounded-xl bg-slate-800/70 hover:bg-slate-700/80 border border-slate-700/60 text-slate-200 text-xs font-bold inline-flex items-center gap-1.5 transition-all focus:outline-none shadow-md"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-400" />
                <span>Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5 text-slate-400" />
                <span>Copy Brief</span>
              </>
            )}
          </motion.button>

          <motion.button
            type="button"
            whileHover={{ scale: 1.03, boxShadow: '0 0 20px rgba(139,92,246,0.4)' }}
            whileTap={{ scale: 0.97 }}
            onClick={() => window.print()}
            className="px-4 py-2 rounded-xl bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-500 hover:to-indigo-500 text-white text-xs font-bold inline-flex items-center gap-1.5 shadow-md transition-all focus:outline-none"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print Prep Kit</span>
          </motion.button>
        </div>
      </div>

      {/* ─────────────────────────────────────────── */}
      {/* MAIN GRID                                   */}
      {/* ─────────────────────────────────────────── */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-5">

        {/* ── LEFT COLUMN (7/12) ── */}
        <div className="lg:col-span-7 space-y-5">

          {/* Questions to ask attorney */}
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="rounded-2xl border border-slate-700/60 bg-slate-900/80 backdrop-blur-xl overflow-hidden"
          >
            {/* Card header */}
            <div className="px-5 py-4 border-b border-slate-700/50 bg-slate-800/40 flex items-center gap-3">
              <div className="w-8 h-8 rounded-lg bg-blue-500/20 border border-blue-500/30 flex items-center justify-center shrink-0">
                <MessageCircleQuestion className="w-4 h-4 text-blue-400" />
              </div>
              <div>
                <h4 className="text-sm font-extrabold text-white tracking-tight">
                  Questions for Your Attorney
                </h4>
                <p className="text-[11px] text-slate-400">{questions.length} prioritised questions</p>
              </div>
            </div>

            <div className="p-4 space-y-3">
              {questions.map((q, idx) => {
                const dots = priorityDot(q.priority);
                return (
                  <motion.div
                    key={q.id}
                    whileHover={{ y: -1 }}
                    transition={{ type: 'spring', stiffness: 350, damping: 25 }}
                    className="p-4 rounded-xl bg-slate-800/60 border border-slate-700/50 space-y-2.5"
                  >
                    <div className="flex items-start justify-between gap-2 flex-wrap">
                      <span className="text-xs font-bold text-white leading-snug">
                        {idx + 1}. {q.topic}
                      </span>
                      <span className={`text-[10px] font-bold px-2.5 py-1 rounded-full inline-flex items-center gap-1.5 border ${priorityBadge(q.priority)}`}>
                        <span className="relative flex h-1.5 w-1.5">
                          <span className={`animate-ping absolute inline-flex h-full w-full rounded-full opacity-70 ${dots.ping}`} />
                          <span className={`relative inline-flex rounded-full h-1.5 w-1.5 ${dots.dot}`} />
                        </span>
                        {q.priority} PRIORITY
                      </span>
                    </div>
                    <p className="text-sm font-semibold text-blue-200 leading-snug">{q.question}</p>
                    <div className="pt-2.5 border-t border-slate-700/40 flex items-start gap-1.5">
                      <HelpCircle className="w-3.5 h-3.5 text-slate-500 shrink-0 mt-0.5" />
                      <p className="text-xs text-slate-300 leading-relaxed">
                        <span className="font-semibold text-slate-200">Context: </span>
                        {q.context}
                      </p>
                    </div>
                  </motion.div>
                );
              })}
            </div>
          </motion.div>

          {/* Missing protective clauses */}
          {missingProtections.length > 0 && (
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className="rounded-2xl border border-violet-500/25 bg-violet-500/5 backdrop-blur-xl overflow-hidden"
            >
              {/* Card header */}
              <div className="px-5 py-4 border-b border-violet-500/20 bg-violet-500/8 flex items-center gap-3">
                <div className="w-8 h-8 rounded-lg bg-violet-500/20 border border-violet-500/30 flex items-center justify-center shrink-0">
                  <FileWarning className="w-4 h-4 text-violet-400" />
                </div>
                <div>
                  <h4 className="text-sm font-extrabold text-white tracking-tight">
                    Crucial Missing Safeguards to Request
                  </h4>
                  <p className="text-[11px] text-slate-400">{missingProtections.length} missing protections identified</p>
                </div>
              </div>

              <div className="p-4 space-y-3">
                {missingProtections.map(m => (
                  <motion.div
                    key={m.id}
                    whileHover={{ y: -1 }}
                    transition={{ type: 'spring', stiffness: 350, damping: 25 }}
                    className="p-4 rounded-xl bg-slate-900/70 border border-violet-500/20 space-y-2.5"
                  >
                    <div className="flex items-start justify-between gap-2 flex-wrap">
                      <strong className="text-sm font-extrabold text-violet-200 leading-tight">{m.title}</strong>
                      <span className={`text-[10px] font-bold px-2.5 py-1 rounded-full border ${importanceBadge(m.importance)}`}>
                        {m.importance} IMPORTANCE
                      </span>
                    </div>
                    <p className="text-sm text-slate-200 leading-relaxed">{m.description}</p>
                    <div className="p-3.5 rounded-lg bg-slate-950/70 border border-violet-800/30 text-xs font-mono text-violet-200 leading-relaxed select-all shadow-inner">
                      &ldquo;{m.recommendedAddition}&rdquo;
                    </div>
                  </motion.div>
                ))}
              </div>
            </motion.div>
          )}
        </div>

        {/* ── RIGHT COLUMN (5/12) ── */}
        <div className="lg:col-span-5 space-y-5">

          {/* Critical red flags checklist */}
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="rounded-2xl border border-emerald-500/25 bg-emerald-500/5 backdrop-blur-xl overflow-hidden"
          >
            {/* Card header with progress */}
            <div className="px-5 py-4 border-b border-emerald-500/20 bg-emerald-500/8 flex items-center justify-between gap-3">
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded-lg bg-emerald-500/20 border border-emerald-500/30 flex items-center justify-center shrink-0">
                  <ClipboardCheck className="w-4 h-4 text-emerald-400" />
                </div>
                <div>
                  <h4 className="text-sm font-extrabold text-white tracking-tight">Immediate Red Flag Actions</h4>
                  <p className="text-[11px] text-slate-400">{criticalChecklist.length} items to review</p>
                </div>
              </div>
              {/* Progress pill */}
              <span className="text-[11px] font-bold px-2.5 py-1 rounded-full bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 shrink-0">
                {checkedCount}/{criticalChecklist.length}
              </span>
            </div>

            {/* Progress bar */}
            {criticalChecklist.length > 0 && (
              <div className="h-1 bg-slate-800">
                <div
                  className="h-full bg-emerald-500 transition-all duration-500"
                  style={{ width: `${(checkedCount / criticalChecklist.length) * 100}%` }}
                />
              </div>
            )}

            <ul className="p-4 space-y-2.5">
              {criticalChecklist.map((item, idx) => {
                const isChecked = checkedItems[idx] || false;
                return (
                  <li key={idx}>
                    <label
                      htmlFor={`check-item-${idx}`}
                      className={`flex items-start gap-3 p-3 rounded-xl border cursor-pointer transition-all group ${
                        isChecked
                          ? 'bg-emerald-500/10 border-emerald-500/25'
                          : 'bg-slate-800/50 border-slate-700/50 hover:border-slate-600/60 hover:bg-slate-800/70'
                      }`}
                    >
                      <div className="relative mt-0.5 shrink-0">
                        <input
                          type="checkbox"
                          id={`check-item-${idx}`}
                          checked={isChecked}
                          onChange={() => toggleCheck(idx)}
                          className="sr-only"
                        />
                        <div className={`w-4 h-4 rounded border-2 flex items-center justify-center transition-all ${
                          isChecked
                            ? 'bg-emerald-500 border-emerald-500'
                            : 'border-slate-600 group-hover:border-slate-400'
                        }`}>
                          {isChecked && (
                            <svg className="w-2.5 h-2.5 text-white" viewBox="0 0 10 10" fill="none">
                              <path d="M1.5 5l2.5 2.5 4.5-4.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                            </svg>
                          )}
                        </div>
                      </div>
                      <span className={`text-sm leading-relaxed font-medium transition-colors ${
                        isChecked ? 'text-slate-400 line-through' : 'text-slate-200'
                      }`}>
                        {item}
                      </span>
                    </label>
                  </li>
                );
              })}
            </ul>
          </motion.div>

          {/* Key negotiation priorities */}
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="rounded-2xl border border-cyan-500/25 bg-cyan-500/5 backdrop-blur-xl overflow-hidden"
          >
            {/* Card header */}
            <div className="px-5 py-4 border-b border-cyan-500/20 bg-cyan-500/8 flex items-center gap-3">
              <div className="w-8 h-8 rounded-lg bg-cyan-500/20 border border-cyan-500/30 flex items-center justify-center shrink-0">
                <Target className="w-4 h-4 text-cyan-400" />
              </div>
              <div>
                <h4 className="text-sm font-extrabold text-white tracking-tight">
                  Counter-Negotiation Strategy
                </h4>
                <p className="text-[11px] text-slate-400">{keyNegotiationPoints.length} recommended priorities</p>
              </div>
            </div>

            <div className="p-4 space-y-2.5">
              {keyNegotiationPoints.map((pt, idx) => (
                <motion.div
                  key={idx}
                  whileHover={{ x: 3 }}
                  transition={{ type: 'spring', stiffness: 400, damping: 25 }}
                  className="flex items-start gap-3 p-3.5 rounded-xl bg-slate-800/60 border border-slate-700/50"
                >
                  <span className="w-6 h-6 rounded-full bg-cyan-500/20 text-cyan-300 border border-cyan-500/30 text-[11px] font-extrabold flex items-center justify-center shrink-0 mt-0.5">
                    {idx + 1}
                  </span>
                  <span className="text-sm text-slate-200 font-medium leading-relaxed">{pt}</span>
                </motion.div>
              ))}
            </div>
          </motion.div>
        </div>
      </div>
    </div>
  );
}
