import { useState } from 'react';
import { motion } from 'motion/react';
import {
  ClipboardCheck,
  HelpCircle,
  ShieldAlert,
  Copy,
  Check,
  FileDown,
  Printer,
  Scale,
  Sparkles,
  AlertTriangle,
  FileWarning,
} from 'lucide-react';
import { LawyerQuestion, MissingProtection, DocumentSummary } from '../types/legal.js';

interface LawyerPrepKitProps {
  summary: DocumentSummary;
  questions: LawyerQuestion[];
  missingProtections: MissingProtection[];
  keyNegotiationPoints: string[];
  criticalChecklist: string[];
  highContrast: boolean;
}

export function LawyerPrepKit({
  summary,
  questions,
  missingProtections,
  keyNegotiationPoints,
  criticalChecklist,
  highContrast,
}: LawyerPrepKitProps) {
  const [copied, setCopied] = useState(false);

  const generateMarkdownBrief = () => {
    let md = `# LEGAL CONSULTATION PREP KIT: ${summary.documentType}\n`;
    md += `Overall Risk Score: ${summary.overallRiskScore}/100 (${summary.overallRiskLevel} Risk)\n`;
    md += `Generated by LexiGuard AI for Legal Assistance & Access\n\n`;
    md += `## EXECUTIVE SUMMARY\n${summary.executiveSummary}\n\n`;

    md += `## 1. CRITICAL RED FLAGS CHECKLIST\n`;
    criticalChecklist.forEach((item, i) => {
      md += `${i + 1}. [ ] ${item}\n`;
    });
    md += `\n`;

    md += `## 2. QUESTIONS TO ASK YOUR ATTORNEY\n`;
    questions.forEach((q, i) => {
      md += `### ${i + 1}. [${q.priority}] ${q.topic}: ${q.question}\n`;
      md += `Context: ${q.context}\n\n`;
    });

    if (missingProtections.length > 0) {
      md += `## 3. MISSING LEGAL SAFEGUARDS TO INSERT\n`;
      missingProtections.forEach((m, i) => {
        md += `### ${i + 1}. ${m.title} (${m.importance})\n`;
        md += `${m.description}\n`;
        md += `Proposed Language: "${m.recommendedAddition}"\n\n`;
      });
    }

    md += `## 4. KEY NEGOTIATION PRIORITIES\n`;
    keyNegotiationPoints.forEach((pt, i) => {
      md += `- ${pt}\n`;
    });

    md += `\n---\nLEGAL NOTICE: Provides educational and informational assistance only; does not replace formal legal counsel.\n`;
    return md;
  };

  const handleCopyBrief = () => {
    const brief = generateMarkdownBrief();
    navigator.clipboard.writeText(brief);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div
      id="lawyer-prep-kit"
      role="region"
      aria-label="Lawyer Consultation Checklist"
      className="space-y-6"
    >
      {/* Top Banner with Action Buttons and Glassmorphism */}
      <motion.div
        initial={{ opacity: 0, y: -6 }}
        animate={{ opacity: 1, y: 0 }}
        className={`p-6 rounded-2xl border backdrop-blur-md transition-colors flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 shadow-xs ${
          highContrast
            ? 'bg-neutral-900/90 border-neutral-700/80 text-white'
            : 'bg-white/85 border-neutral-200/80 text-neutral-900'
        }`}
      >
        <div>
          <div className="flex items-center gap-2 mb-1.5">
            <span className="p-1.5 rounded-lg bg-indigo-100 dark:bg-indigo-950/60 text-indigo-700 dark:text-indigo-300">
              <Scale className="w-4 h-4" aria-hidden="true" />
            </span>
            <span className="text-xs font-bold uppercase tracking-wider text-indigo-700 dark:text-indigo-300">
              Attorney Prep & Strategy Kit
            </span>
          </div>
          <h3 className="text-xl font-bold tracking-tight text-neutral-900 dark:text-white">
            Actionable Lawyer Consultation Briefing
          </h3>
          <p className="text-xs text-neutral-600 dark:text-neutral-400 mt-1 max-w-2xl leading-relaxed">
            Maximize your consultation efficiency and save hundreds in hourly attorney fees by bringing this prioritized issue list, missing clause checklist, and strategic negotiation counter-proposals.
          </p>
        </div>

        <div className="flex items-center gap-2.5 shrink-0">
          <motion.button
            type="button"
            whileHover={{ scale: 1.03 }}
            whileTap={{ scale: 0.97 }}
            onClick={handleCopyBrief}
            aria-label="Copy consultation briefing to clipboard"
            className="px-4 py-2 rounded-xl bg-neutral-100/90 dark:bg-neutral-800 hover:bg-neutral-200/90 text-neutral-800 dark:text-neutral-200 border border-neutral-300/80 dark:border-neutral-700 text-xs font-semibold inline-flex items-center gap-1.5 transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500 shadow-2xs"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" aria-hidden="true" />
                <span>Briefing Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5 text-neutral-700 dark:text-neutral-300" aria-hidden="true" />
                <span>Copy to Clipboard</span>
              </>
            )}
          </motion.button>

          <motion.button
            type="button"
            whileHover={{ scale: 1.03 }}
            whileTap={{ scale: 0.97 }}
            onClick={handlePrint}
            aria-label="Print consultation prep kit"
            className="px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold inline-flex items-center gap-1.5 shadow-2xs transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <Printer className="w-3.5 h-3.5" aria-hidden="true" />
            <span>Print Prep Kit</span>
          </motion.button>
        </div>
      </motion.div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Questions to Ask Counsel */}
        <div className="lg:col-span-7 space-y-5">
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className={`p-6 rounded-2xl border backdrop-blur-md transition-all shadow-xs ${
              highContrast
                ? 'bg-neutral-900/90 border-neutral-700/80 text-white'
                : 'bg-white/85 border-neutral-200/80 text-neutral-900'
            }`}
          >
            <h4 className="text-sm font-bold uppercase tracking-wider text-neutral-700 dark:text-neutral-300 mb-4 flex items-center gap-2">
              <HelpCircle className="w-4 h-4 text-blue-600 dark:text-blue-400" aria-hidden="true" />
              <span>Prioritized Questions for Your Attorney ({questions.length})</span>
            </h4>

            <div className="space-y-3.5">
              {questions.map((q, idx) => {
                const isHigh = q.priority === 'HIGH';
                const isMed = q.priority === 'MEDIUM';

                return (
                  <motion.div
                    key={q.id}
                    whileHover={{ y: -2 }}
                    transition={{ type: 'spring', stiffness: 350, damping: 25 }}
                    className="p-4 rounded-xl bg-neutral-50/80 dark:bg-neutral-950/40 border border-neutral-200/70 dark:border-neutral-800/70 text-xs sm:text-sm space-y-2 shadow-2xs"
                  >
                    <div className="flex items-center justify-between gap-2">
                      <span className="text-xs font-bold text-neutral-900 dark:text-white">
                        {idx + 1}. {q.topic}
                      </span>
                      <span
                        className={`text-[10px] font-bold px-2.5 py-1 rounded-full inline-flex items-center gap-1.5 ${
                          isHigh
                            ? 'bg-rose-100 text-rose-700 dark:bg-rose-950/50 dark:text-rose-300 border border-rose-200/70 dark:border-rose-900/50'
                            : isMed
                            ? 'bg-amber-100 text-amber-800 dark:bg-amber-950/50 dark:text-amber-300 border border-amber-200/70 dark:border-amber-900/50'
                            : 'bg-neutral-100 text-neutral-700 dark:bg-neutral-800 dark:text-neutral-300 border border-neutral-200 dark:border-neutral-700'
                        }`}
                      >
                        <span className="relative flex h-1.5 w-1.5">
                          <span
                            className={`animate-ping absolute inline-flex h-full w-full rounded-full opacity-75 ${
                              isHigh ? 'bg-rose-400' : isMed ? 'bg-amber-400' : 'bg-neutral-400'
                            }`}
                          />
                          <span
                            className={`relative inline-flex rounded-full h-1.5 w-1.5 ${
                              isHigh ? 'bg-rose-500' : isMed ? 'bg-amber-500' : 'bg-neutral-500'
                            }`}
                          />
                        </span>
                        <span>{q.priority} PRIORITY</span>
                      </span>
                    </div>
                    <p className="font-semibold text-blue-900 dark:text-blue-200 leading-snug">{q.question}</p>
                    <p className="text-xs text-neutral-600 dark:text-neutral-400 pt-1.5 border-t border-neutral-200/60 dark:border-neutral-800/60 leading-relaxed">
                      <strong className="text-neutral-800 dark:text-neutral-200">Context:</strong> {q.context}
                    </p>
                  </motion.div>
                );
              })}
            </div>
          </motion.div>

          {/* Missing Protective Clauses Checklist */}
          {missingProtections.length > 0 && (
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className={`p-6 rounded-2xl border backdrop-blur-md transition-all shadow-xs ${
                highContrast
                  ? 'bg-neutral-900/90 border-neutral-700/80 text-white'
                  : 'bg-white/85 border-neutral-200/80 text-neutral-900'
              }`}
            >
              <h4 className="text-sm font-bold uppercase tracking-wider text-purple-900 dark:text-purple-300 mb-4 flex items-center gap-2">
                <FileWarning className="w-4 h-4 text-purple-600 dark:text-purple-400" aria-hidden="true" />
                <span>Crucial Missing Safeguards to Request ({missingProtections.length})</span>
              </h4>

              <div className="space-y-3.5">
                {missingProtections.map(m => (
                  <motion.div
                    key={m.id}
                    whileHover={{ y: -2 }}
                    transition={{ type: 'spring', stiffness: 350, damping: 25 }}
                    className="p-4 rounded-xl bg-purple-50/60 dark:bg-purple-950/20 border border-purple-200/70 dark:border-purple-900/50 text-xs space-y-2 shadow-2xs"
                  >
                    <div className="flex items-center justify-between">
                      <strong className="font-bold text-purple-950 dark:text-purple-200 text-xs sm:text-sm">
                        {m.title}
                      </strong>
                      <span className="text-[10px] font-bold px-2.5 py-1 rounded-full bg-purple-100 dark:bg-purple-900/60 text-purple-800 dark:text-purple-200 border border-purple-200 dark:border-purple-800">
                        {m.importance} IMPORTANCE
                      </span>
                    </div>
                    <p className="text-neutral-700 dark:text-neutral-300 leading-relaxed">{m.description}</p>
                    <div className="p-3 rounded-lg bg-white/90 dark:bg-neutral-950/60 border border-purple-100 dark:border-purple-900/40 text-purple-900 dark:text-purple-200 font-mono text-[11px] leading-relaxed shadow-inner select-all">
                      &ldquo;{m.recommendedAddition}&rdquo;
                    </div>
                  </motion.div>
                ))}
              </div>
            </motion.div>
          )}
        </div>

        {/* Right Column: Red Flag Checklist & Negotiation Points */}
        <div className="lg:col-span-5 space-y-5">
          {/* Critical Red Flags Checklist */}
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className={`p-6 rounded-2xl border backdrop-blur-md transition-all shadow-xs ${
              highContrast
                ? 'bg-neutral-900/90 border-neutral-700/80 text-white'
                : 'bg-white/85 border-neutral-200/80 text-neutral-900'
            }`}
          >
            <h4 className="text-sm font-bold uppercase tracking-wider text-neutral-700 dark:text-neutral-300 mb-3.5 flex items-center gap-2">
              <ClipboardCheck className="w-4 h-4 text-emerald-600 dark:text-emerald-400" aria-hidden="true" />
              <span>Immediate Red Flag Action Items</span>
            </h4>

            <ul className="space-y-2.5">
              {criticalChecklist.map((item, idx) => (
                <li key={idx} className="flex items-start gap-2.5 text-xs text-neutral-800 dark:text-neutral-200 leading-relaxed">
                  <input
                    type="checkbox"
                    id={`check-item-${idx}`}
                    className="mt-0.5 rounded border-neutral-300 dark:border-neutral-700 text-blue-600 focus:ring-blue-500 cursor-pointer"
                  />
                  <label htmlFor={`check-item-${idx}`} className="cursor-pointer font-medium">
                    {item}
                  </label>
                </li>
              ))}
            </ul>
          </motion.div>

          {/* Key Negotiation Priorities */}
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className={`p-6 rounded-2xl border backdrop-blur-md transition-all shadow-xs ${
              highContrast
                ? 'bg-neutral-900/90 border-neutral-700/80 text-white'
                : 'bg-white/85 border-neutral-200/80 text-neutral-900'
            }`}
          >
            <h4 className="text-sm font-bold uppercase tracking-wider text-neutral-700 dark:text-neutral-300 mb-3.5 flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-blue-600 dark:text-blue-400" aria-hidden="true" />
              <span>Recommended Counter-Negotiation Strategy</span>
            </h4>

            <div className="space-y-2.5">
              {keyNegotiationPoints.map((pt, idx) => (
                <motion.div
                  key={idx}
                  whileHover={{ x: 2 }}
                  className="p-3.5 rounded-xl bg-neutral-50/80 dark:bg-neutral-950/40 border border-neutral-200/70 dark:border-neutral-800/70 text-xs text-neutral-800 dark:text-neutral-200 flex items-start gap-2.5 shadow-2xs"
                >
                  <span className="w-5 h-5 rounded-full bg-blue-100 dark:bg-blue-900/60 text-blue-800 dark:text-blue-200 text-[10px] font-bold flex items-center justify-center shrink-0 mt-0.5">
                    {idx + 1}
                  </span>
                  <span className="font-medium leading-relaxed">{pt}</span>
                </motion.div>
              ))}
            </div>
          </motion.div>
        </div>
      </div>
    </div>
  );
}

